version: '2'

services:
  db:
    build: ./sql/docker/
    ports:
      - "54321:5432"
    #environment:
    #  - POSTGRES_PASSWORD=password
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_DB=postgres
    env_file:
      - ./../common.env