version: '2'

services:
  App1:
    image: nginx
    ports:
      - "10001:80"
    networks:
      - "netName1"
    volumes:
      - ./nginx/:/mnt
  App2:
    image: nginx
    ports:
      - "10002:80"
    networks:
      - "netName2"
    volumes:
      - ./build:/usr/share/nginx/html
  App3:
    image: nginx
    ports:
      - "10003:80"
    networks:
      - "netName2"
    volumes:
      - ./build:/usr/share/nginx/html
  Db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  Server1:
    image: "kanban"
    ports:
      - "8000:8000"
    depends_on:
      - "Db"
    environment:
      - ENV_PORT=8000
  Server2:
    image: "kanban"
    ports:
      - "8001:8001"
    depends_on:
      - "Db"
    environment:
      - ENV_PORT=8001
networks:
  netName1:
    driver: bridge
  netName2:
    driver: bridge