version: '2'

services:
  App1:
    image: nginx
    ports:
      - "10001:80"
    networks:
      - "netName1"
    volumes:
      - ./nginx/:/mnt
  App2:
    image: nginx
    ports:
      - "10002:80"
    networks:
      - "netName2"
    volumes:
      - ./build:/usr/share/nginx/html
  App3:
    image: nginx
    ports:
      - "10003:80"
    networks:
      - "netName2"
    volumes:
      - ./build:/usr/share/nginx/html
networks:
  netName1:
    driver: bridge
  netName2:
    driver: bridge